### ISSUE TITLE
Fails with Node.js ≥ 16.12.0 due to loader hook API change

### ISSUE THREAD

**Issue by andersk** [istanbuljs/esm-loader-hook#6]
This hook worked with Node 16.11.1 but fails with ≥ 16.12.0. It now raises `(node:40) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: transformSource`, and fails to collect any coverage data. This is due to an incompatible [change](https://github.com/nodejs/node/blob/v16.12.0/doc/changelogs/CHANGELOG_V16.md#experimental-esm-loader-hooks-api
) in the ESM loader hook API. Incompatible changes to this experimental API were not unexpected, of course, but it’s worth having an issue noting that this has now occurred and the package is no longer functional.

Minimal test case:

**`package.json`**

```json
{
  "dependencies": {
    "@istanbuljs/esm-loader-hook": "^0.1.2",
    "nyc": "^15.1.0"
  },
  "type": "module"
}
```

**`test.js`**

```js
import "./module.js";
```

**`module.js`**

```js
console.log("Hello, world!");
export {};
```

```console
$ npx nyc node --experimental-loader=@istanbuljs/esm-loader-hook test.js
(node:2394052) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2394052) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: transformSource
Hello, world!
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
```

**Comment by vassudanagunta** [comment]
I've confirmed this. I'll update the StackOverflow setup instructions[^1][^2] for this once I know what the plan is going forward. 

[^1]: https://stackoverflow.com/questions/62509699/nyc-mocha-es6-modules

[^2]: https://stackoverflow.com/questions/67913176/how-to-implement-istanbul-coverage-with-selenium-and-mocha/68095739?noredirect=1#comment124669336_68095739
